# Generated by Django 4.0.3 on 2022-05-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_user_tag_user_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
    ]
