# Generated by Django 4.0.3 on 2022-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
