# Generated by Django 4.0.3 on 2022-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='input',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
