# Generated by Django 4.0.3 on 2022-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_input_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
