# Generated by Django 4.0.3 on 2022-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_alter_input_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='tag',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
    ]
