# Generated by Django 4.0.4 on 2022-07-05 01:51

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_input_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='tag',
        ),
        migrations.AddField(
            model_name='input',
            name='tag',
            field=models.CharField(blank=True, max_length=20, verbose_name=community.models.Tag),
        ),
    ]
