# Generated by Django 4.0.4 on 2022-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_remove_input_tag_input_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(max_length=2)),
                ('i', models.CharField(max_length=2)),
                ('n', models.CharField(max_length=2)),
                ('s', models.CharField(max_length=2)),
                ('f', models.CharField(max_length=2)),
                ('t', models.CharField(max_length=2)),
                ('p', models.CharField(max_length=2)),
                ('j', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='mbti',
            field=models.ManyToManyField(blank=True, to='community.mbti'),
        ),
        migrations.AddField(
            model_name='tour',
            name='mbti',
            field=models.ManyToManyField(blank=True, to='community.mbti'),
        ),
    ]
