# Generated by Django 4.0.4 on 2022-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_mbti_input_mbti_tour_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='e',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='f',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='i',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='j',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='n',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='p',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='s',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='t',
        ),
        migrations.AddField(
            model_name='mbti',
            name='name',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
