# Generated by Django 4.0.4 on 2022-07-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_remove_mbti_e_remove_mbti_f_remove_mbti_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='mbti',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='mbti',
        ),
        migrations.DeleteModel(
            name='Mbti',
        ),
    ]
