# Generated by Django 4.0.3 on 2022-07-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_restaurant_visitcnt_stay_visitcnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='restaurant_url',
            new_name='stay_url',
        ),
    ]
