# Generated by Django 4.0.3 on 2022-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='stay',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tour',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
